// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahE3RdO-4a15sLnq0I-_aiSBe800SaX4',
    appId: '1:1094332014212:web:781a8204987fc1280c6cd1',
    messagingSenderId: '1094332014212',
    projectId: 'doctro-8e02e',
    authDomain: 'doctro-8e02e.firebaseapp.com',
    storageBucket: 'doctro-8e02e.appspot.com',
    measurementId: 'G-RXBD1HKW97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQptUl717EM61d8bn8KcQtkD6h6JaSqg',
    appId: '1:1094332014212:android:b26f278e989b3e5a0c6cd1',
    messagingSenderId: '1094332014212',
    projectId: 'doctro-8e02e',
    storageBucket: 'doctro-8e02e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv26agys9_p0UOTnt941qnfJOZ9mRhtfA',
    appId: '1:1094332014212:ios:cbf92b3eb3e5e5dd0c6cd1',
    messagingSenderId: '1094332014212',
    projectId: 'doctro-8e02e',
    storageBucket: 'doctro-8e02e.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv26agys9_p0UOTnt941qnfJOZ9mRhtfA',
    appId: '1:1094332014212:ios:2c152977cd87f71d0c6cd1',
    messagingSenderId: '1094332014212',
    projectId: 'doctro-8e02e',
    storageBucket: 'doctro-8e02e.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
